[tools]
uv = "latest"
"dotnet:MarkdownSnippets.Tool" = "latest"

[env.'_'.python]
venv = { path = ".venv", create = true, uv_create_args = ["--seed", "--quiet"] }

[tasks]
"pip-install" = "uv pip install -r requirements.dev.txt --quiet"
test = { run = "python -m pytest --quiet --junitxml=junit-reports/TEST-results.xml", depends = ["pip-install"] }
mypy = { run = "python -m mypy .", depends = ["pip-install"] }
lint = { run = "python -m pylint .", depends = ["pip-install"] }
integration = { run = "python test__mypy_accepts_our_packages.py", depends = ["pip-install"] }

[tasks.ruff]
run = [
    "python -m ruff format .",
    "python -m ruff check --extend-select I --fix ."
]
depends = ["pip-install"]

[settings]
# we put the python version in the .python-version file instead of here so that it's easy to override in the CI matrix
idiomatic_version_file_enable_tools = ["python"]
# dotnet backend is experimental
experimental = true
