[tools]
uv = "latest"
"dotnet:MarkdownSnippets.Tool" = "latest"

[env.'_'.python]
venv = { path = ".venv", create = true, uv_create_args = ["--seed", "--quiet"] }

[tasks]
install_python_deps = "uv pip install -r requirements.dev.txt --quiet"
test = "python -m pytest --quiet --junitxml=junit-reports/TEST-results.xml"
mypy = "python -m mypy ."
integration = "python test__mypy_accepts_our_packages.py"
isort = "python -m isort ."
black = "python -m black ."

[settings]
# we put the python version in the .python-version file instead of here so that it's easy to override in the CI matrix
idiomatic_version_file_enable_tools = ["python"]
# dotnet backend is experimental
experimental = true
