[tools]
uv = "latest"

[env.'_'.python.venv]
path = ".venv"
create = true
uv_create_args = ["--seed", "--quiet"]

[tasks]
"pip-install" = "uv pip install -r requirements.dev.txt --quiet"
build_and_test.depends = ["test", "mypy", "lint", "integration"]

[tasks.test]
run = "python -m pytest --quiet --junitxml=junit-reports/TEST-results.xml"
depends = ["pip-install"]

[tasks.mypy]
run = "python -m mypy ."
depends = ["pip-install"]

[tasks.lint]
run = "python -m pylint ."
depends = ["pip-install"]

[tasks.integration]
run = "python test__mypy_accepts_our_packages.py"
depends = ["pip-install"]

[tasks.ruff]
run = [
    "python -m ruff format .",
    "python -m ruff check --extend-select I --fix .",
]
depends = ["pip-install"]

[settings]
# we put the python version in the .python-version file instead of here so that it's easy to override in the CI matrix
idiomatic_version_file_enable_tools = ["python"]
