[tools]
uv = "latest"

[tasks]
install_python_deps = "python -m pip install -r requirements.dev.txt --quiet --no-warn-script-location"
test = "python -m pytest --quiet --junitxml=test-reports/pytest.xml"
mypy = "python -m mypy ."
integration = "python test__mypy_accepts_our_packages.py"
isort = "python -m isort ."
black = "python -m black ."

[settings]
# we put the python version in the .python-version file instead of here so that it's easy to override in the CI matrix
idiomatic_version_file_enable_tools = ["python"]
