#!/bin/bash

COUNT_FILE="../../.ignore/count.txt"

if [ ! -f "$COUNT_FILE" ]; then
    echo 0 > "$COUNT_FILE"
fi

count=$(cat "$COUNT_FILE")
count=$((count + 1))
echo $count > "$COUNT_FILE"

# Return exit code 0 if problems are found (count < 4), otherwise return 1.
if [ $count -lt 4 ]; then
    exit 0
else
    exit 1
fi