sequenceDiagram
    actor User
    participant TestRunner
    participant ApprovalTest
    participant ApprovalTest_Class

    User->>TestRunner: Start
    ApprovalTest->>ApprovalTest_Class: implicit class-level setup
    create participant LogFile
    ApprovalTest_Class->>LogFile: open/truncate


    %% Test 1
    note over TestRunner,LogFile: Test 1
    TestRunner->>ApprovalTest: Run Test 1

    note right of ApprovalTest: Arrange
    note right of ApprovalTest: Act
    note right of ApprovalTest: Assert
    ApprovalTest->>ApprovalTest_Class: approve()

    create participant ApprovedFile
    ApprovalTest_Class->>ApprovedFile: open/truncate
    ApprovalTest_Class->>ApprovedFile: write()  
    ApprovalTest_Class->>LogFile: write()   
    ApprovalTest->>TestRunner: Pass-or-Fail Test 1

    %% Test 2
    note over TestRunner,LogFile: Test 2
    TestRunner->>ApprovalTest: Run Test 2..n
    ApprovalTest->>ApprovalTest_Class: approve()

    create participant ApprovedFile_2..n
    ApprovalTest_Class->>ApprovedFile_2..n: open/truncate
    ApprovalTest_Class->>ApprovedFile_2..n: write
    ApprovalTest_Class->>LogFile: write()   
    ApprovalTest->>TestRunner: Pass-or-Fail Test 2
 
    %% Test ...n
    note over TestRunner,LogFile: Test ...n
    ApprovalTest->>TestRunner: Pass-or-Fail Test ...
    ApprovalTest->>TestRunner: Pass-or-Fail Test n

    note over TestRunner,LogFile: End all tests

    TestRunner->>User: Pass-or-Fail SESSION

    Note over ApprovedFile_2..n,LogFile: Files persists after test session



sequenceDiagram
    actor User
    participant TestRunner
    participant ApprovalTest
    participant ApprovalTest_Class
    participant ApprovedFile
    participant ApprovedFile_2..n
    participant LogFile

    User->>TestRunner: Start

    activate TestRunner

    ApprovalTest->>ApprovalTest_Class: implicit class-level setup
    activate LogFile
    ApprovalTest_Class->>LogFile: open/truncate


    note over TestRunner,LogFile: Test 1
    TestRunner->>ApprovalTest: Run Test 1

    note right of ApprovalTest: Arrange
    note right of ApprovalTest: Act
    note right of ApprovalTest: Assert
    ApprovalTest->>ApprovalTest_Class: approve()
    ApprovalTest_Class->>ApprovedFile: write
    activate ApprovedFile
    
    ApprovalTest_Class->>LogFile: register file (write/append)   
    ApprovalTest->>TestRunner: Pass-or-Fail Test 1

    note over TestRunner,LogFile: Test 2..n
    TestRunner->>ApprovalTest: Run Test 2..n
    ApprovalTest->>ApprovalTest_Class: approve()
    ApprovalTest_Class->>+ApprovedFile_2..n: write
    activate ApprovedFile_2..n
    ApprovalTest_Class->>LogFile: register file access   
    ApprovalTest->>TestRunner: Pass-or-Fail Test 2
    ApprovalTest->>TestRunner:  . . .
    ApprovalTest->>TestRunner: Pass-or-Fail Test n

    note over TestRunner,LogFile: End all tests

    TestRunner->>User: Pass-or-Fail SESSION

    deactivate TestRunner

    Note over ApprovedFile,LogFile: Files persists after test session

    %% Note right of ApprovedFile: ApprovedFile persists
    %% Note right of LogFile: LogFile persists

    deactivate LogFile
    deactivate ApprovedFile
    deactivate ApprovedFile_2..n


