name: validate dependabot.yml schema conformance
on:
  push:
    paths:
      - .github/dependabot.yml
      - .github/workflows/dependabot_validation.yml
  pull_request:
    paths:
      - .github/dependabot.yml
      - .github/workflows/dependabot_validation.yml
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cardinalby/schema-validator-action@v3
        with:
          file: '.github/dependabot.yml'
          schema: 'https://json.schemastore.org/dependabot-2.0.json'
          mode: 'lax'  # Error: Keyword not supported: "x-intellij-enum-metadata" at https://json.schemastore.org/dependabot-2.0.json#
